# Generated by Django 3.0.5 on 2021-04-09 17:12

import dcmotor_rest_api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdStr', models.CharField(max_length=100)),
                ('faultval', models.DecimalField(decimal_places=4, max_digits=9)),
                ('faultPredict', djongo.models.fields.ArrayField(model_container=dcmotor_rest_api.models.Fault_Predict, model_form_class=dcmotor_rest_api.models.FaultPredictForm)),
                ('speedVal', models.DecimalField(decimal_places=4, max_digits=9)),
                ('currentVal', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
    ]
